version: "3.8"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    profiles:
      - monitoring
    volumes:
      - uptime_kuma_data:/app/data
    networks:
      - public_net
      - backend_net

volumes:
  uptime_kuma_data:
