"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { CustomerShell, extractErrorMessage, useCustomer } from "../../../customer";

type Plan = { id: number; plan_code: string; name: string; traffic_limit_bytes: number; price: string; currency: string };
type Order = { id: number; order_no: string; amount: string; currency: string; status: string; payment_status: string };
function OrderForm() { const { request } = useCustomer(); const [plans, setPlans] = useState<Plan[]>([]); const [planId, setPlanId] = useState(""); const [order, setOrder] = useState<Order | null>(null); const [message, setMessage] = useState(""); const [error, setError] = useState(""); useEffect(() => { request("/plans").then(async (r) => { const rows = await r.json() as Plan[]; const available = rows.filter((p) => ["PLAN_50GB", "PLAN_100GB", "PLAN_200GB", "PLAN_500GB"].includes(p.plan_code)); setPlans(available); if (available[0]) setPlanId(new URLSearchParams(window.location.search).get("plan_id") ?? String(available[0].id)); }); }, [request]); const selected = plans.find((p) => String(p.id) === planId); async function create(event: FormEvent) { event.preventDefault(); setError(""); const response = await request("/orders", { method: "POST", body: JSON.stringify({ plan_id: Number(planId), client_request_id: crypto.randomUUID() }) }); const body = await response.json().catch(() => ({})) as Order & { detail?: string }; if (!response.ok) { setError(extractErrorMessage(body, "下单失败")); return; } setOrder(body); } async function noticePaid() { if (!order) return; const response = await request(`/orders/${order.id}/payment-notice`, { method: "POST" }); const body = await response.json().catch(() => ({})) as { detail?: string }; if (!response.ok) { setError(extractErrorMessage(body, "通知失败")); return; } setMessage("已通知管理员，请等待人工确认收款。"); } return <>{error && <p className="notice error">{error}</p>}{!order ? <form className="panel form-panel" onSubmit={create}><label>选择套餐<select value={planId} onChange={(e) => setPlanId(e.target.value)} required>{plans.map((p) => <option key={p.id} value={p.id}>{p.name} · {p.traffic_limit_bytes / (1024 ** 3)}GB · {p.price} {p.currency}</option>)}</select></label><button type="submit">创建订单</button></form> : <section className="panel order-payment"><p className="eyebrow">订单已创建</p><h2>{order.order_no}</h2><p>套餐：{selected?.name} · 应付：<strong>{order.amount} {order.currency}</strong></p><div className="payment-placeholder"><span>微信收款码占位</span><span>支付宝收款码占位</span></div><p className="muted">请完成转账后点击下方按钮，系统会通过 Telegram 通知管理员。</p><button onClick={() => void noticePaid()} disabled={Boolean(message)}>我已付款</button>{message && <p className="notice">{message}</p>}<p><Link href="/orders">查看订单列表</Link></p></section>}</>; }
export default function NewOrderPage() { return <CustomerShell title="新建订单"><OrderForm /></CustomerShell>; }
